/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppIcon: typeof import('./components/AppIcon.vue')['default']
    Button: typeof import('./components/ui/button/Button.vue')['default']
    ConfettiCanvas: typeof import('./components/ConfettiCanvas.vue')['default']
    CreateRoomForm: typeof import('./components/CreateRoomForm.vue')['default']
    DarkModeToggle: typeof import('./components/DarkModeToggle.vue')['default']
    Dialog: typeof import('./components/Dialog.vue')['default']
    DividerWithLabel: typeof import('./components/DividerWithLabel.vue')['default']
    EstimateOptions: typeof import('./components/EstimateOptions.vue')['default']
    Footer: typeof import('./components/Footer.vue')['default']
    Header: typeof import('./components/Header.vue')['default']
    ImageTextSection: typeof import('./components/ImageTextSection.vue')['default']
    JoinRoomForm: typeof import('./components/JoinRoomForm.vue')['default']
    PlayerCard: typeof import('./components/PlayerCard.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
